### ISSUE TITLE
entrega 1

### ISSUE THREAD

**Issue by brm-cortesc** [brm-viracachac/brm-estelar-bmw-arpc#1]
Este es el corte del Site para la activación de BBB - Clear 2 @brm-viracachac

**Comment by brm-cortesc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CORTE LANDING](https://trello.com/c/wWlF8Dfs/5-corte-landing)

**Comment by brm-viracachac** [comment]
Esta actualizado el de Estelar
