### ISSUE TITLE
Hay textos que están en bold y en la visual están light

### ISSUE THREAD

**Issue by brm-cortesc** [brm-viracachac/brm-estelar-bmw-arpc#13]

**Comment by brm-viracachac** [comment]
Es otra fuente que no me deja convertir a web por eso solo utilicé la BEBAS  que esta en la mayoría del sitio

**Comment by brm-cortesc** [comment]
Si no se puede con la bebas light, busque una de soporte porque es imposible de leer texto corrido con bebas

**Comment by brm-viracachac** [comment]
se cambio la fuente a Arial layout.styl
