### ISSUE TITLE
Scroll

### ISSUE THREAD

**Issue by brm-cortesc** [brm-viracachac/brm-estelar-bmw-arpc#17]
El sito es scrolleable y se ocultó el scroll <- este comportamiento por defecto del navegador no debería quitarse, no es un site fullscreen y en este momenot tampoco se puede navegar de otra forma que no sea con los botones de los formularios, si no es el scroll entonces unos indicadores para poder navegar sin depender solo de elementos del UI que se ocultan.

**Comment by brm-viracachac** [comment]
El sitio debe ir en una sola dirección por que los datos se envian, no debe volver a atras

**Comment by brm-cortesc** [comment]
Ahora tenemos doble scroll en todas las resoluciones
