### ISSUE TITLE
optimización CSS

### ISSUE THREAD

**Issue by brm-cortesc** [brm-viracachac/brm-estelar-bmw-arpc#56]
Se están llamando modulos de bootstrap que no se están usando.

**Comment by brm-viracachac** [comment]
se comentaron las lineas del import en bootstrap.config.styl

**Comment by brm-cortesc** [comment]
En la carpeta CSS tiene un css frontend.min.css que está quedando pegado en el compilado final y esto genera que el publicable se vea toteado.
