### ISSUE TITLE
Aspecto imagen interna - formulario principal

### ISSUE THREAD

**Issue by brm-perezd** [brm-viracachac/brm-estelar-bmw-arpc#72]
La imagen debe ocupar menor espacio y la terraza de la casa debe quedar sobre el fondo, tal y como se ve en el screeshot aprobado.

Ver screenshot 15.

**Comment by brm-viracachac** [comment]
la imagen ya no se sobre pone , pero el fondo  no puede cambiar porque las secciones se ocultan en cada validacion
