### ISSUE TITLE
Seleccione ciudad

### ISSUE THREAD

**Issue by brm-perezd** [brm-viracachac/brm-estelar-bmw-arpc#81]
Si dejo los campos vacíos de ciudad y departamento, luego intento actualizar datos y luego selecciono de nuevo el departamento me carga la ciudad, pero me dice que la seleccione, colocar opción seleccione para cuando se carguen las ciudades.

Ver screenshot 24.

**Comment by brm-martinezs** [comment]
Ya quedo corregido
