### ISSUE TITLE
Aclaración de mayúsculas y minúsculas campos de formulario.

### ISSUE THREAD

**Issue by brm-perezd** [brm-viracachac/brm-estelar-bmw-arpc#92]
Lo que es texto no se puede guardar completamente en mayúscula.

(Ver en diseño como hacer para que permita escribir minúsculas y en desarrollo comprobar, después de cambios de diseño, que se permita guardar minúsculas)

Ver screenshot 35.

**Comment by brm-viracachac** [comment]
se ajusto el texto del index.pug y la funte se paso a arial

**Comment by brm-martinezs** [comment]
Se quito la opción para que inserte mayusculas y minusculas en la BD
